/nologo
/optimize+
/debug-
/unsafe-
/warn:0
/out:c:/builds/mindpowered/logic/shopping-cart/build/vcs/csharp/bin/shoppingcart.dll
/target:library
/reference:c:/builds/mindpowered/logic/shopping-cart/build/vcs/csharp/bin/maglev.dll
src\shoppingcart\CartModel.cs
src\EnumValue.cs
src\shoppingcart\ShoppingCart.cs
src\shoppingcart\ItemModel.cs
src\Type.cs
src\shoppingcart\CartRepository.cs
src\shoppingcart\ItemRepository.cs
src\shoppingcart\ShoppingCartLogic.cs
src\UInt.cs
src\mindpowered\shoppingcart\ShoppingCart.cs