// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class CartRepository : global::haxe.lang.HxObject {
		
		static CartRepository() {
			unchecked{
				#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{3254785, 958206052}, new string[]{"Add", "Remove"});
			}
		}
		#line default
		
		public CartRepository(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public CartRepository(global::maglev.MagLev bus) {
			#line 11 "/my-component/src/shoppingcart/CartRepository.hx"
			global::shoppingcart.CartRepository.__hx_ctor_shoppingcart_CartRepository(this, bus);
		}
		#line default
		
		protected static void __hx_ctor_shoppingcart_CartRepository(global::shoppingcart.CartRepository __hx_this, global::maglev.MagLev bus) {
			#line 12 "/my-component/src/shoppingcart/CartRepository.hx"
			__hx_this.bus = bus;
			__hx_this.carts = new global::Array<object>();
			#line 14 "/my-component/src/shoppingcart/CartRepository.hx"
			__hx_this.counter = 0;
		}
		#line default
		
		public global::maglev.MagLev bus;
		
		public global::Array<object> carts;
		
		public int counter;
		
		public virtual void Add(global::shoppingcart.CartModel cart, global::haxe.lang.Function callback) {
			unchecked {
				#line 30 "/my-component/src/shoppingcart/CartRepository.hx"
				string cartId = global::Std.@string(this.counter);
				this.counter += 1;
				#line 32 "/my-component/src/shoppingcart/CartRepository.hx"
				cart.id = cartId;
				this.carts.push(cart);
				#line 34 "/my-component/src/shoppingcart/CartRepository.hx"
				callback.__hx_invoke1_o(default(double), cartId);
			}
			#line default
		}
		
		
		public virtual void Remove(string cartId, global::haxe.lang.Function callback) {
			#line 38 "/my-component/src/shoppingcart/CartRepository.hx"
			{
				#line 38 "/my-component/src/shoppingcart/CartRepository.hx"
				int _g = 0;
				#line 38 "/my-component/src/shoppingcart/CartRepository.hx"
				global::Array<object> _g1 = this.carts;
				#line 38 "/my-component/src/shoppingcart/CartRepository.hx"
				while (( _g < _g1.length )) {
					#line 38 "/my-component/src/shoppingcart/CartRepository.hx"
					global::shoppingcart.CartModel cart = ((global::shoppingcart.CartModel) (_g1[_g]) );
					#line 38 "/my-component/src/shoppingcart/CartRepository.hx"
					 ++ _g;
					if (( cart.id == cartId )) {
						#line 40 "/my-component/src/shoppingcart/CartRepository.hx"
						this.carts.@remove(cart);
						callback.__hx_invoke0_o();
						#line 42 "/my-component/src/shoppingcart/CartRepository.hx"
						return;
					}
					
				}
				
			}
			
			#line 45 "/my-component/src/shoppingcart/CartRepository.hx"
			callback.__hx_invoke0_o();
		}
		#line default
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
				switch (hash) {
					case 492416764:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						this.counter = ((int) (@value) );
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return @value;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
				switch (hash) {
					case 492416764:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						this.counter = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return @value;
					}
					
					
					case 1092617875:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						this.carts = ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (@value) ))) );
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return @value;
					}
					
					
					case 4899648:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						this.bus = ((global::maglev.MagLev) (@value) );
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return @value;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
				switch (hash) {
					case 958206052:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Remove", 958206052)) );
					}
					
					
					case 3254785:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Add", 3254785)) );
					}
					
					
					case 492416764:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return this.counter;
					}
					
					
					case 1092617875:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return this.carts;
					}
					
					
					case 4899648:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return this.bus;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
				switch (hash) {
					case 492416764:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return ((double) (this.counter) );
					}
					
					
					default:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
				switch (hash) {
					case 958206052:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						this.Remove(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						break;
					}
					
					
					case 3254785:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						this.Add(((global::shoppingcart.CartModel) (dynargs[0]) ), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						break;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
			baseArr.push("counter");
			#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
			baseArr.push("carts");
			#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
			baseArr.push("bus");
			#line 5 "/my-component/src/shoppingcart/CartRepository.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


