// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class CartModel : global::haxe.lang.HxObject {
		
		public CartModel(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public CartModel() {
			#line 5 "/my-component/src/shoppingcart/CartModel.hx"
			global::shoppingcart.CartModel.__hx_ctor_shoppingcart_CartModel(this);
		}
		#line default
		
		protected static void __hx_ctor_shoppingcart_CartModel(global::shoppingcart.CartModel __hx_this) {
		}
		
		
		public string id;
		
		public string storeId;
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/shoppingcart/CartModel.hx"
				switch (hash) {
					case 1152110108:
					{
						#line 3 "/my-component/src/shoppingcart/CartModel.hx"
						this.storeId = global::haxe.lang.Runtime.toString(@value);
						#line 3 "/my-component/src/shoppingcart/CartModel.hx"
						return @value;
					}
					
					
					case 23515:
					{
						#line 3 "/my-component/src/shoppingcart/CartModel.hx"
						this.id = global::haxe.lang.Runtime.toString(@value);
						#line 3 "/my-component/src/shoppingcart/CartModel.hx"
						return @value;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/shoppingcart/CartModel.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/shoppingcart/CartModel.hx"
				switch (hash) {
					case 1152110108:
					{
						#line 3 "/my-component/src/shoppingcart/CartModel.hx"
						return this.storeId;
					}
					
					
					case 23515:
					{
						#line 3 "/my-component/src/shoppingcart/CartModel.hx"
						return this.id;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/shoppingcart/CartModel.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 3 "/my-component/src/shoppingcart/CartModel.hx"
			baseArr.push("storeId");
			#line 3 "/my-component/src/shoppingcart/CartModel.hx"
			baseArr.push("id");
			#line 3 "/my-component/src/shoppingcart/CartModel.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


