// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ItemRepository : global::haxe.lang.HxObject {
		
		static ItemRepository() {
			unchecked{
				#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{3254785, 306504849, 770176554, 838800523, 958206052}, new string[]{"Add", "FindByCartIdAndIdx", "Edit", "FindByCartId", "Remove"});
			}
		}
		#line default
		
		public ItemRepository(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ItemRepository(global::maglev.MagLev bus) {
			#line 11 "/my-component/src/shoppingcart/ItemRepository.hx"
			global::shoppingcart.ItemRepository.__hx_ctor_shoppingcart_ItemRepository(this, bus);
		}
		#line default
		
		protected static void __hx_ctor_shoppingcart_ItemRepository(global::shoppingcart.ItemRepository __hx_this, global::maglev.MagLev bus) {
			#line 12 "/my-component/src/shoppingcart/ItemRepository.hx"
			__hx_this.bus = bus;
			__hx_this.items = new global::haxe.ds.StringMap<object>();
		}
		#line default
		
		public global::maglev.MagLev bus;
		
		public global::haxe.ds.StringMap<object> items;
		
		public virtual void Add(global::shoppingcart.ItemModel item, global::haxe.lang.Function callback) {
			#line 17 "/my-component/src/shoppingcart/ItemRepository.hx"
			if ( ! (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).exists(item.cartId)) ) {
				#line 18 "/my-component/src/shoppingcart/ItemRepository.hx"
				global::haxe.IMap<string, object> this1 = this.items;
				#line 18 "/my-component/src/shoppingcart/ItemRepository.hx"
				string k = item.cartId;
				#line 18 "/my-component/src/shoppingcart/ItemRepository.hx"
				global::Array<object> v = new global::Array<object>();
				#line 18 "/my-component/src/shoppingcart/ItemRepository.hx"
				((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (this1) ))) ).@set(k, v);
			}
			
			#line 20 "/my-component/src/shoppingcart/ItemRepository.hx"
			int idx = ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).@get(item.cartId)).@value) ))) ).length;
			item.idx = idx;
			#line 22 "/my-component/src/shoppingcart/ItemRepository.hx"
			((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).@get(item.cartId)).@value) ))) ).push(item);
			callback.__hx_invoke1_o(((double) (idx) ), global::haxe.lang.Runtime.undefined);
		}
		#line default
		
		public virtual void Edit(global::shoppingcart.ItemModel item, global::haxe.lang.Function callback) {
			#line 45 "/my-component/src/shoppingcart/ItemRepository.hx"
			((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).@get(item.cartId)).@value) ))) )[item.idx] = item;
			callback.__hx_invoke0_o();
		}
		#line default
		
		public virtual void Remove(string cartId, int idx, global::haxe.lang.Function callback) {
			#line 50 "/my-component/src/shoppingcart/ItemRepository.hx"
			((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).@get(cartId)).@value) ))) )[idx] = null;
			callback.__hx_invoke0_o();
		}
		#line default
		
		public virtual void FindByCartId(string cartId, global::haxe.lang.Function callback) {
			#line 55 "/my-component/src/shoppingcart/ItemRepository.hx"
			if (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).exists(cartId)) {
				#line 56 "/my-component/src/shoppingcart/ItemRepository.hx"
				callback.__hx_invoke1_o(default(double), ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).@get(cartId)).@value) ))) ));
			}
			else {
				#line 58 "/my-component/src/shoppingcart/ItemRepository.hx"
				callback.__hx_invoke1_o(default(double), new global::Array<object>());
			}
			
		}
		#line default
		
		public virtual void FindByCartIdAndIdx(string cartId, int idx, global::haxe.lang.Function callback) {
			#line 63 "/my-component/src/shoppingcart/ItemRepository.hx"
			if (((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).exists(cartId)) {
				#line 64 "/my-component/src/shoppingcart/ItemRepository.hx"
				if (( ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).@get(cartId)).@value) ))) ).length > idx )) {
					#line 65 "/my-component/src/shoppingcart/ItemRepository.hx"
					callback.__hx_invoke1_o(default(double), ((global::shoppingcart.ItemModel) (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) ((((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((global::haxe.IMap<string, object>) (this.items) )) ))) ).@get(cartId)).@value) ))) )[idx]) ));
					return;
				}
				
			}
			
			#line 69 "/my-component/src/shoppingcart/ItemRepository.hx"
			callback.__hx_invoke1_o(default(double), null);
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
				switch (hash) {
					case 1108126720:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						this.items = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (@value) ))) );
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return @value;
					}
					
					
					case 4899648:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						this.bus = ((global::maglev.MagLev) (@value) );
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return @value;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
				switch (hash) {
					case 306504849:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "FindByCartIdAndIdx", 306504849)) );
					}
					
					
					case 838800523:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "FindByCartId", 838800523)) );
					}
					
					
					case 958206052:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Remove", 958206052)) );
					}
					
					
					case 770176554:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Edit", 770176554)) );
					}
					
					
					case 3254785:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Add", 3254785)) );
					}
					
					
					case 1108126720:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return this.items;
					}
					
					
					case 4899648:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return this.bus;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
				switch (hash) {
					case 306504849:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						this.FindByCartIdAndIdx(global::haxe.lang.Runtime.toString(dynargs[0]), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), ((global::haxe.lang.Function) (dynargs[2]) ));
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						break;
					}
					
					
					case 838800523:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						this.FindByCartId(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						break;
					}
					
					
					case 958206052:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						this.Remove(global::haxe.lang.Runtime.toString(dynargs[0]), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), ((global::haxe.lang.Function) (dynargs[2]) ));
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						break;
					}
					
					
					case 770176554:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						this.Edit(((global::shoppingcart.ItemModel) (dynargs[0]) ), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						break;
					}
					
					
					case 3254785:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						this.Add(((global::shoppingcart.ItemModel) (dynargs[0]) ), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						break;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
			baseArr.push("items");
			#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
			baseArr.push("bus");
			#line 5 "/my-component/src/shoppingcart/ItemRepository.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


