// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ItemModel : global::haxe.lang.HxObject {
		
		public ItemModel(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ItemModel() {
			#line 5 "/my-component/src/shoppingcart/ItemModel.hx"
			global::shoppingcart.ItemModel.__hx_ctor_shoppingcart_ItemModel(this);
		}
		#line default
		
		protected static void __hx_ctor_shoppingcart_ItemModel(global::shoppingcart.ItemModel __hx_this) {
		}
		
		
		public string cartId;
		
		public int idx;
		
		public string itemId;
		
		public int qty;
		
		public double price;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
				switch (hash) {
					case 1217089161:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						this.price = ((double) (@value) );
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return @value;
					}
					
					
					case 5645366:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						this.qty = ((int) (@value) );
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return @value;
					}
					
					
					case 5243965:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						this.idx = ((int) (@value) );
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return @value;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
				switch (hash) {
					case 1217089161:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						this.price = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return @value;
					}
					
					
					case 5645366:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						this.qty = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return @value;
					}
					
					
					case 151629774:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						this.itemId = global::haxe.lang.Runtime.toString(@value);
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return @value;
					}
					
					
					case 5243965:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						this.idx = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return @value;
					}
					
					
					case 988124635:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						this.cartId = global::haxe.lang.Runtime.toString(@value);
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return @value;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
				switch (hash) {
					case 1217089161:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return this.price;
					}
					
					
					case 5645366:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return this.qty;
					}
					
					
					case 151629774:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return this.itemId;
					}
					
					
					case 5243965:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return this.idx;
					}
					
					
					case 988124635:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return this.cartId;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
				switch (hash) {
					case 1217089161:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return this.price;
					}
					
					
					case 5645366:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return ((double) (this.qty) );
					}
					
					
					case 5243965:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return ((double) (this.idx) );
					}
					
					
					default:
					{
						#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
			baseArr.push("price");
			#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
			baseArr.push("qty");
			#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
			baseArr.push("itemId");
			#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
			baseArr.push("idx");
			#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
			baseArr.push("cartId");
			#line 3 "/my-component/src/shoppingcart/ItemModel.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


