// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic : global::haxe.lang.HxObject {
		
		static ShoppingCartLogic() {
			unchecked{
				#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{51449041, 214267984, 615899533, 816044828, 965739415, 1330524084, 1535697261, 2048936610}, new string[]{"CountItems", "GetCartSummary", "UpdateQty", "Create", "RemoveItem", "AddItem", "Clear", "ListItems"});
			}
		}
		#line default
		
		public ShoppingCartLogic(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ShoppingCartLogic(global::shoppingcart.CartRepository cartRepo, global::shoppingcart.ItemRepository itemRepo) {
			#line 6 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			global::shoppingcart.ShoppingCartLogic.__hx_ctor_shoppingcart_ShoppingCartLogic(this, cartRepo, itemRepo);
		}
		#line default
		
		protected static void __hx_ctor_shoppingcart_ShoppingCartLogic(global::shoppingcart.ShoppingCartLogic __hx_this, global::shoppingcart.CartRepository cartRepo, global::shoppingcart.ItemRepository itemRepo) {
			#line 7 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			__hx_this.cartRepo = cartRepo;
			__hx_this.itemRepo = itemRepo;
		}
		#line default
		
		public global::shoppingcart.CartRepository cartRepo;
		
		public global::shoppingcart.ItemRepository itemRepo;
		
		public virtual void Create(string storeId, global::haxe.lang.Function callback) {
			#line 12 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			global::shoppingcart.CartModel cart = new global::shoppingcart.CartModel();
			cart.storeId = storeId;
			#line 14 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.cartRepo.Add(cart, new global::shoppingcart.ShoppingCartLogic_Create_14__Fun(callback));
		}
		#line default
		
		public virtual void AddItem(string cartId, string itemId, int qty, double price, global::haxe.lang.Function callback) {
			#line 19 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			global::shoppingcart.ItemModel item = new global::shoppingcart.ItemModel();
			item.cartId = cartId;
			#line 21 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			item.itemId = itemId;
			item.qty = qty;
			#line 23 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			item.price = price;
			this.itemRepo.Add(item, new global::shoppingcart.ShoppingCartLogic_AddItem_24__Fun(callback));
		}
		#line default
		
		public virtual void ListItems(string cartId, global::haxe.lang.Function callback) {
			#line 29 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.itemRepo.FindByCartId(cartId, new global::shoppingcart.ShoppingCartLogic_ListItems_29__Fun(callback));
		}
		#line default
		
		public virtual void RemoveItem(string cartId, int idx, global::haxe.lang.Function callback) {
			#line 44 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.itemRepo.Remove(cartId, idx, new global::shoppingcart.ShoppingCartLogic_RemoveItem_44__Fun(callback));
		}
		#line default
		
		public virtual void UpdateQty(string cartId, int idx, int qty, global::haxe.lang.Function callback) {
			#line 48 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			global::shoppingcart.ShoppingCartLogic _gthis = this;
			this.itemRepo.FindByCartIdAndIdx(cartId, idx, new global::shoppingcart.ShoppingCartLogic_UpdateQty_49__Fun(qty, callback, _gthis));
		}
		#line default
		
		public virtual void CountItems(string cartId, global::haxe.lang.Function callback) {
			#line 57 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.itemRepo.FindByCartId(cartId, new global::shoppingcart.ShoppingCartLogic_CountItems_57__Fun(callback));
		}
		#line default
		
		public virtual void GetCartSummary(string cartId, global::haxe.lang.Function callback) {
			#line 63 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.itemRepo.FindByCartId(cartId, new global::shoppingcart.ShoppingCartLogic_GetCartSummary_63__Fun(callback));
		}
		#line default
		
		public virtual void Clear(string cartId, global::haxe.lang.Function callback) {
			#line 80 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.cartRepo.Remove(cartId, new global::shoppingcart.ShoppingCartLogic_Clear_80__Fun(callback));
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				switch (hash) {
					case 681824037:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.itemRepo = ((global::shoppingcart.ItemRepository) (@value) );
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return @value;
					}
					
					
					case 1976504946:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.cartRepo = ((global::shoppingcart.CartRepository) (@value) );
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return @value;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				switch (hash) {
					case 1535697261:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Clear", 1535697261)) );
					}
					
					
					case 214267984:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "GetCartSummary", 214267984)) );
					}
					
					
					case 51449041:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "CountItems", 51449041)) );
					}
					
					
					case 615899533:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "UpdateQty", 615899533)) );
					}
					
					
					case 965739415:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "RemoveItem", 965739415)) );
					}
					
					
					case 2048936610:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "ListItems", 2048936610)) );
					}
					
					
					case 1330524084:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "AddItem", 1330524084)) );
					}
					
					
					case 816044828:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Create", 816044828)) );
					}
					
					
					case 681824037:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return this.itemRepo;
					}
					
					
					case 1976504946:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return this.cartRepo;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				switch (hash) {
					case 1535697261:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.Clear(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						break;
					}
					
					
					case 214267984:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.GetCartSummary(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						break;
					}
					
					
					case 51449041:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.CountItems(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						break;
					}
					
					
					case 615899533:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.UpdateQty(global::haxe.lang.Runtime.toString(dynargs[0]), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[2])) ), ((global::haxe.lang.Function) (dynargs[3]) ));
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						break;
					}
					
					
					case 965739415:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.RemoveItem(global::haxe.lang.Runtime.toString(dynargs[0]), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), ((global::haxe.lang.Function) (dynargs[2]) ));
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						break;
					}
					
					
					case 2048936610:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.ListItems(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						break;
					}
					
					
					case 1330524084:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.AddItem(global::haxe.lang.Runtime.toString(dynargs[0]), global::haxe.lang.Runtime.toString(dynargs[1]), ((int) (global::haxe.lang.Runtime.toInt(dynargs[2])) ), ((double) (global::haxe.lang.Runtime.toDouble(dynargs[3])) ), ((global::haxe.lang.Function) (dynargs[4]) ));
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						break;
					}
					
					
					case 816044828:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						this.Create(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						break;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			baseArr.push("itemRepo");
			#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			baseArr.push("cartRepo");
			#line 3 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic_Create_14__Fun : global::haxe.lang.Function {
		
		public ShoppingCartLogic_Create_14__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 15 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 14 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			string cartId = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (global::haxe.lang.Runtime.toString(__fn_float1)) : (global::haxe.lang.Runtime.toString(__fn_dyn1)) );
			this.callback.__hx_invoke1_o(default(double), cartId);
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic_AddItem_24__Fun : global::haxe.lang.Function {
		
		public ShoppingCartLogic_AddItem_24__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 25 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 24 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			int idx = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float1) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn1)) )) );
			this.callback.__hx_invoke1_o(((double) (idx) ), global::haxe.lang.Runtime.undefined);
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic_ListItems_29__Fun : global::haxe.lang.Function {
		
		static ShoppingCartLogic_ListItems_29__Fun() {
			unchecked{
				#line 29 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5243965, 5645366, 151629774, 1217089161}, new string[]{"idx", "qty", "itemId", "price"});
			}
		}
		#line default
		
		public ShoppingCartLogic_ListItems_29__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 29 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 29 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			global::Array<object> items = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (((object) (__fn_float1) )) ))) )) : (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (__fn_dyn1) ))) )) );
			global::Array<object> list = new global::Array<object>();
			#line 31 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			{
				#line 31 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				int _g = 0;
				#line 31 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				while (( _g < items.length )) {
					#line 31 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
					global::shoppingcart.ItemModel item = ((global::shoppingcart.ItemModel) (items[_g]) );
					#line 31 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
					 ++ _g;
					object cartItem = new global::haxe.lang.DynamicObject(new int[]{151629774}, new object[]{item.itemId}, new int[]{5243965, 5645366, 1217089161}, new double[]{((double) (item.idx) ), ((double) (item.qty) ), item.price});
					#line 38 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
					list.push(cartItem);
				}
				
			}
			
			#line 40 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback.__hx_invoke1_o(default(double), list);
			#line 29 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic_RemoveItem_44__Fun : global::haxe.lang.Function {
		
		public ShoppingCartLogic_RemoveItem_44__Fun(global::haxe.lang.Function callback) : base(0, 0) {
			#line 45 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke0_o() {
			#line 45 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback.__hx_invoke0_o();
			#line 45 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic_UpdateQty_51__Fun : global::haxe.lang.Function {
		
		public ShoppingCartLogic_UpdateQty_51__Fun(global::haxe.lang.Function callback) : base(0, 0) {
			#line 52 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke0_o() {
			#line 52 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback.__hx_invoke0_o();
			#line 52 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic_UpdateQty_49__Fun : global::haxe.lang.Function {
		
		public ShoppingCartLogic_UpdateQty_49__Fun(int qty, global::haxe.lang.Function callback, global::shoppingcart.ShoppingCartLogic _gthis) : base(1, 0) {
			#line 49 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.qty = qty;
			#line 49 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback = callback;
			#line 49 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 49 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			global::shoppingcart.ItemModel item = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::shoppingcart.ItemModel) (((object) (__fn_float1) )) )) : (((global::shoppingcart.ItemModel) (__fn_dyn1) )) );
			item.qty = this.qty;
			#line 51 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this._gthis.itemRepo.Edit(item, new global::shoppingcart.ShoppingCartLogic_UpdateQty_51__Fun(this.callback));
			#line 49 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			return null;
		}
		#line default
		
		public int qty;
		
		public global::haxe.lang.Function callback;
		
		public global::shoppingcart.ShoppingCartLogic _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic_CountItems_57__Fun : global::haxe.lang.Function {
		
		public ShoppingCartLogic_CountItems_57__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 57 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 57 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			global::Array<object> items = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (((object) (__fn_float1) )) ))) )) : (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (__fn_dyn1) ))) )) );
			int count = items.length;
			#line 59 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback.__hx_invoke1_o(((double) (count) ), global::haxe.lang.Runtime.undefined);
			#line 57 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic_GetCartSummary_63__Fun : global::haxe.lang.Function {
		
		static ShoppingCartLogic_GetCartSummary_63__Fun() {
			unchecked{
				#line 63 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{338842564, 1108126720}, new string[]{"total", "items"});
			}
		}
		#line default
		
		public ShoppingCartLogic_GetCartSummary_63__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 63 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 63 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			global::Array<object> items = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (((object) (__fn_float1) )) ))) )) : (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (__fn_dyn1) ))) )) );
			double total = ((double) (0) );
			#line 65 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			int count = 0;
			{
				#line 66 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				int _g = 0;
				#line 66 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
				while (( _g < items.length )) {
					#line 66 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
					global::shoppingcart.ItemModel item = ((global::shoppingcart.ItemModel) (items[_g]) );
					#line 66 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
					 ++ _g;
					if (( item != null )) {
						#line 68 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
						total += ( item.qty * item.price );
						count += item.qty;
					}
					
				}
				
			}
			
			#line 72 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			object summary = new global::haxe.lang.DynamicObject(new int[]{}, new object[]{}, new int[]{338842564, 1108126720}, new double[]{total, ((double) (count) )});
			#line 76 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback.__hx_invoke1_o(default(double), summary);
			#line 63 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCartLogic_Clear_80__Fun : global::haxe.lang.Function {
		
		public ShoppingCartLogic_Clear_80__Fun(global::haxe.lang.Function callback) : base(0, 0) {
			#line 81 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke0_o() {
			#line 81 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			this.callback.__hx_invoke0_o();
			#line 81 "/my-component/src/shoppingcart/ShoppingCartLogic.hx"
			return null;
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}


