// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart : global::haxe.lang.HxObject {
		
		static ShoppingCart() {
			unchecked{
				#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5243965, 5541879, 5645366, 13816588, 151629774, 338842564, 957002115, 1108126720, 1217089161}, new string[]{"idx", "obj", "qty", "SuppressWarnings", "itemId", "total", "registerMyMethods", "items", "price"});
				#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
				{
					#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment", "checkstyle:LocalVariableName", "checkstyle:MultipleStringLiterals", "checkstyle:MagicNumber"})})}, new int[]{}, new double[]{});
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						global::shoppingcart.ShoppingCart.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public ShoppingCart(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ShoppingCart(global::maglev.MagLev maglev) {
			#line 15 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::shoppingcart.ShoppingCart.__hx_ctor_shoppingcart_ShoppingCart(this, maglev);
		}
		#line default
		
		protected static void __hx_ctor_shoppingcart_ShoppingCart(global::shoppingcart.ShoppingCart __hx_this, global::maglev.MagLev maglev) {
			#line 16 "/my-component/src/shoppingcart/ShoppingCart.hx"
			__hx_this.maglev = maglev;
			__hx_this.logic = new global::shoppingcart.ShoppingCartLogic(new global::shoppingcart.CartRepository(((global::maglev.MagLev) (maglev) )), new global::shoppingcart.ItemRepository(((global::maglev.MagLev) (maglev) )));
			#line 21 "/my-component/src/shoppingcart/ShoppingCart.hx"
			__hx_this.registerMyMethods();
		}
		#line default
		
		public static object __meta__;
		
		public global::maglev.MagLev maglev;
		
		public global::shoppingcart.ShoppingCartLogic logic;
		
		public virtual void registerMyMethods() {
			#line 23 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::shoppingcart.ShoppingCart _gthis = this;
			this.maglev.register("ShoppingCart.Create", global::maglev.MagLevFunction.fromFunction(new global::shoppingcart.ShoppingCart_registerMyMethods_24__Fun(_gthis)));
			#line 32 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.maglev.register("ShoppingCart.AddItem", global::maglev.MagLevFunction.fromFunction(new global::shoppingcart.ShoppingCart_registerMyMethods_32__Fun(_gthis)));
			#line 43 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.maglev.register("ShoppingCart.ListItems", global::maglev.MagLevFunction.fromFunction(new global::shoppingcart.ShoppingCart_registerMyMethods_43__Fun(_gthis)));
			#line 60 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.maglev.register("ShoppingCart.RemoveItem", global::maglev.MagLevFunction.fromFunction(new global::shoppingcart.ShoppingCart_registerMyMethods_60__Fun(_gthis)));
			#line 69 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.maglev.register("ShoppingCart.UpdateQty", global::maglev.MagLevFunction.fromFunction(new global::shoppingcart.ShoppingCart_registerMyMethods_69__Fun(_gthis)));
			#line 79 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.maglev.register("ShoppingCart.CountItems", global::maglev.MagLevFunction.fromFunction(new global::shoppingcart.ShoppingCart_registerMyMethods_79__Fun(_gthis)));
			#line 87 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.maglev.register("ShoppingCart.GetCartSummary", global::maglev.MagLevFunction.fromFunction(new global::shoppingcart.ShoppingCart_registerMyMethods_87__Fun(_gthis)));
			#line 98 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.maglev.register("ShoppingCart.Clear", global::maglev.MagLevFunction.fromFunction(new global::shoppingcart.ShoppingCart_registerMyMethods_98__Fun(_gthis)));
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
				switch (hash) {
					case 2029246814:
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						this.logic = ((global::shoppingcart.ShoppingCartLogic) (@value) );
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						return @value;
					}
					
					
					case 858513194:
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						this.maglev = ((global::maglev.MagLev) (@value) );
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						return @value;
					}
					
					
					default:
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
				switch (hash) {
					case 957002115:
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "registerMyMethods", 957002115)) );
					}
					
					
					case 2029246814:
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						return this.logic;
					}
					
					
					case 858513194:
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						return this.maglev;
					}
					
					
					default:
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
				switch (hash) {
					case 957002115:
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						this.registerMyMethods();
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						break;
					}
					
					
					default:
					{
						#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
			baseArr.push("logic");
			#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
			baseArr.push("maglev");
			#line 12 "/my-component/src/shoppingcart/ShoppingCart.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_27__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_27__Fun(global::maglev.MagLevResult result) : base(1, 0) {
			#line 28 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result = result;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 27 "/my-component/src/shoppingcart/ShoppingCart.hx"
			string cartId = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (global::haxe.lang.Runtime.toString(__fn_float1)) : (global::haxe.lang.Runtime.toString(__fn_dyn1)) );
			this.result.setResult(global::maglev.MagLevString.fromString(cartId));
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult result;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_24__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_24__Fun(global::shoppingcart.ShoppingCart _gthis) : base(1, 0) {
			#line 24 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 24 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string storeId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 26 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::maglev.MagLevResult result = global::maglev.MagLevResult.createAsync();
			this._gthis.logic.Create(storeId, new global::shoppingcart.ShoppingCart_registerMyMethods_27__Fun(result));
			#line 30 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return result;
		}
		#line default
		
		public global::shoppingcart.ShoppingCart _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_38__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_38__Fun(global::maglev.MagLevResult result) : base(1, 0) {
			#line 39 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result = result;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 38 "/my-component/src/shoppingcart/ShoppingCart.hx"
			int idx = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float1) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn1)) )) );
			this.result.setResult(global::maglev.MagLevNumber.fromInt(idx));
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult result;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_32__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_32__Fun(global::shoppingcart.ShoppingCart _gthis) : base(1, 0) {
			#line 32 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 32 "/my-component/src/shoppingcart/ShoppingCart.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string cartId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 34 "/my-component/src/shoppingcart/ShoppingCart.hx"
				string itemId = (((global::maglev.MagLevString) (args.@get(1)) )).getString();
				int qty = (((global::maglev.MagLevNumber) (args.@get(2)) )).getInt();
				#line 36 "/my-component/src/shoppingcart/ShoppingCart.hx"
				double price = (((global::maglev.MagLevNumber) (args.@get(3)) )).getFloat();
				global::maglev.MagLevResult result = global::maglev.MagLevResult.createAsync();
				#line 38 "/my-component/src/shoppingcart/ShoppingCart.hx"
				this._gthis.logic.AddItem(cartId, itemId, qty, price, new global::shoppingcart.ShoppingCart_registerMyMethods_38__Fun(result));
				#line 41 "/my-component/src/shoppingcart/ShoppingCart.hx"
				return result;
			}
			#line default
		}
		
		
		public global::shoppingcart.ShoppingCart _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_46__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_46__Fun(global::maglev.MagLevResult result) : base(1, 0) {
			#line 46 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result = result;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 46 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::Array<object> items = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (((object) (__fn_float1) )) ))) )) : (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (__fn_dyn1) ))) )) );
			global::maglev.MagLevArray arr = global::maglev.MagLevArray.create();
			#line 48 "/my-component/src/shoppingcart/ShoppingCart.hx"
			{
				#line 48 "/my-component/src/shoppingcart/ShoppingCart.hx"
				int _g = 0;
				#line 48 "/my-component/src/shoppingcart/ShoppingCart.hx"
				while (( _g < items.length )) {
					#line 48 "/my-component/src/shoppingcart/ShoppingCart.hx"
					object item = items[_g];
					#line 48 "/my-component/src/shoppingcart/ShoppingCart.hx"
					 ++ _g;
					global::maglev.MagLevObject obj = global::maglev.MagLevObject.create();
					#line 50 "/my-component/src/shoppingcart/ShoppingCart.hx"
					obj.@set("idx", global::maglev.MagLevNumber.fromInt(((int) (global::haxe.lang.Runtime.getField_f(item, "idx", 5243965, true)) )));
					obj.@set("itemId", global::maglev.MagLevString.fromString(global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.getField(item, "itemId", 151629774, true))));
					#line 52 "/my-component/src/shoppingcart/ShoppingCart.hx"
					obj.@set("qty", global::maglev.MagLevNumber.fromFloat(global::haxe.lang.Runtime.getField_f(item, "qty", 5645366, true)));
					obj.@set("price", global::maglev.MagLevNumber.fromFloat(global::haxe.lang.Runtime.getField_f(item, "price", 1217089161, true)));
					#line 54 "/my-component/src/shoppingcart/ShoppingCart.hx"
					arr.push(obj);
				}
				
			}
			
			#line 56 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result.setResult(arr);
			#line 46 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult result;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_43__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_43__Fun(global::shoppingcart.ShoppingCart _gthis) : base(1, 0) {
			#line 43 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 43 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string cartId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 45 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::maglev.MagLevResult result = global::maglev.MagLevResult.createAsync();
			this._gthis.logic.ListItems(cartId, new global::shoppingcart.ShoppingCart_registerMyMethods_46__Fun(result));
			#line 58 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return result;
		}
		#line default
		
		public global::shoppingcart.ShoppingCart _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_64__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_64__Fun(global::maglev.MagLevResult result) : base(0, 0) {
			#line 65 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result = result;
		}
		#line default
		
		public override object __hx_invoke0_o() {
			#line 65 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result.setResult(global::maglev.MagLevNull.create());
			#line 65 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult result;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_60__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_60__Fun(global::shoppingcart.ShoppingCart _gthis) : base(1, 0) {
			#line 60 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 60 "/my-component/src/shoppingcart/ShoppingCart.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string cartId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 62 "/my-component/src/shoppingcart/ShoppingCart.hx"
				int idx = (((global::maglev.MagLevNumber) (args.@get(1)) )).getInt();
				global::maglev.MagLevResult result = global::maglev.MagLevResult.createAsync();
				#line 64 "/my-component/src/shoppingcart/ShoppingCart.hx"
				this._gthis.logic.RemoveItem(cartId, idx, new global::shoppingcart.ShoppingCart_registerMyMethods_64__Fun(result));
				#line 67 "/my-component/src/shoppingcart/ShoppingCart.hx"
				return result;
			}
			#line default
		}
		
		
		public global::shoppingcart.ShoppingCart _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_74__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_74__Fun(global::maglev.MagLevResult result) : base(0, 0) {
			#line 75 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result = result;
		}
		#line default
		
		public override object __hx_invoke0_o() {
			#line 75 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result.setResult(global::maglev.MagLevNull.create());
			#line 75 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult result;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_69__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_69__Fun(global::shoppingcart.ShoppingCart _gthis) : base(1, 0) {
			#line 69 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 69 "/my-component/src/shoppingcart/ShoppingCart.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string cartId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 71 "/my-component/src/shoppingcart/ShoppingCart.hx"
				int idx = (((global::maglev.MagLevNumber) (args.@get(1)) )).getInt();
				int qty = (((global::maglev.MagLevNumber) (args.@get(2)) )).getInt();
				#line 73 "/my-component/src/shoppingcart/ShoppingCart.hx"
				global::maglev.MagLevResult result = global::maglev.MagLevResult.createAsync();
				this._gthis.logic.UpdateQty(cartId, idx, qty, new global::shoppingcart.ShoppingCart_registerMyMethods_74__Fun(result));
				#line 77 "/my-component/src/shoppingcart/ShoppingCart.hx"
				return result;
			}
			#line default
		}
		
		
		public global::shoppingcart.ShoppingCart _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_82__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_82__Fun(global::maglev.MagLevResult result) : base(1, 0) {
			#line 83 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result = result;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 82 "/my-component/src/shoppingcart/ShoppingCart.hx"
			int count = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((int) (__fn_float1) )) : (((int) (global::haxe.lang.Runtime.toInt(__fn_dyn1)) )) );
			this.result.setResult(global::maglev.MagLevNull.create());
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult result;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_79__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_79__Fun(global::shoppingcart.ShoppingCart _gthis) : base(1, 0) {
			#line 79 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 79 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string cartId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 81 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::maglev.MagLevResult result = global::maglev.MagLevResult.createAsync();
			this._gthis.logic.CountItems(cartId, new global::shoppingcart.ShoppingCart_registerMyMethods_82__Fun(result));
			#line 85 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return result;
		}
		#line default
		
		public global::shoppingcart.ShoppingCart _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_90__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_90__Fun(global::maglev.MagLevResult result) : base(1, 0) {
			#line 90 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result = result;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 90 "/my-component/src/shoppingcart/ShoppingCart.hx"
			object summary = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			global::maglev.MagLevObject obj = global::maglev.MagLevObject.create();
			#line 92 "/my-component/src/shoppingcart/ShoppingCart.hx"
			obj.@set("items", global::maglev.MagLevNumber.fromInt(((int) (global::haxe.lang.Runtime.getField_f(summary, "items", 1108126720, true)) )));
			obj.@set("total", global::maglev.MagLevNumber.fromFloat(global::haxe.lang.Runtime.getField_f(summary, "total", 338842564, true)));
			#line 94 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result.setResult(obj);
			#line 90 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult result;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_87__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_87__Fun(global::shoppingcart.ShoppingCart _gthis) : base(1, 0) {
			#line 87 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 87 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string cartId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 89 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::maglev.MagLevResult result = global::maglev.MagLevResult.createAsync();
			this._gthis.logic.GetCartSummary(cartId, new global::shoppingcart.ShoppingCart_registerMyMethods_90__Fun(result));
			#line 96 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return result;
		}
		#line default
		
		public global::shoppingcart.ShoppingCart _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_101__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_101__Fun(global::maglev.MagLevResult result) : base(0, 0) {
			#line 102 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result = result;
		}
		#line default
		
		public override object __hx_invoke0_o() {
			#line 102 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this.result.setResult(global::maglev.MagLevNull.create());
			#line 102 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return null;
		}
		#line default
		
		public global::maglev.MagLevResult result;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace shoppingcart {
	public class ShoppingCart_registerMyMethods_98__Fun : global::haxe.lang.Function {
		
		public ShoppingCart_registerMyMethods_98__Fun(global::shoppingcart.ShoppingCart _gthis) : base(1, 0) {
			#line 98 "/my-component/src/shoppingcart/ShoppingCart.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 98 "/my-component/src/shoppingcart/ShoppingCart.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			global::maglev.MagLevResult result = global::maglev.MagLevResult.createAsync();
			#line 100 "/my-component/src/shoppingcart/ShoppingCart.hx"
			string cartId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			this._gthis.logic.Clear(cartId, new global::shoppingcart.ShoppingCart_registerMyMethods_101__Fun(result));
			#line 104 "/my-component/src/shoppingcart/ShoppingCart.hx"
			return result;
		}
		#line default
		
		public global::shoppingcart.ShoppingCart _gthis;
		
	}
}


