// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._HashMap {
	public sealed class HashMap_Impl_ {
		
		static HashMap_Impl_() {
			unchecked{
				#line 34 "/opt/haxe/std/haxe/ds/HashMap.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{125111323}, new string[]{"hashCode"});
			}
		}
		#line default
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public static global::haxe.ds._HashMap.HashMapData<K, V> _new<K, V>() {
			#line 38 "/opt/haxe/std/haxe/ds/HashMap.hx"
			global::haxe.ds._HashMap.HashMapData<K, V> this1 = new global::haxe.ds._HashMap.HashMapData<K, V>();
			#line 38 "/opt/haxe/std/haxe/ds/HashMap.hx"
			return ((global::haxe.ds._HashMap.HashMapData<K, V>) (this1) );
		}
		#line default
		
		public static void @set<K, V>(global::haxe.ds._HashMap.HashMapData<K, V> this1, K k, V v) {
			#line 46 "/opt/haxe/std/haxe/ds/HashMap.hx"
			this1.keys.@set(((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(k, "hashCode", 125111323, null))) ), k);
			this1.values.@set(((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(k, "hashCode", 125111323, null))) ), v);
		}
		#line default
		
		public static global::haxe.lang.Null<V> @get<K, V>(global::haxe.ds._HashMap.HashMapData<K, V> this1, K k) {
			#line 54 "/opt/haxe/std/haxe/ds/HashMap.hx"
			return this1.values.@get(((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(k, "hashCode", 125111323, null))) ));
		}
		#line default
		
		public static bool exists<K, V>(global::haxe.ds._HashMap.HashMapData<K, V> this1, K k) {
			#line 61 "/opt/haxe/std/haxe/ds/HashMap.hx"
			return this1.values.exists(((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(k, "hashCode", 125111323, null))) ));
		}
		#line default
		
		public static bool @remove<K, V>(global::haxe.ds._HashMap.HashMapData<K, V> this1, K k) {
			#line 68 "/opt/haxe/std/haxe/ds/HashMap.hx"
			this1.values.@remove(((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(k, "hashCode", 125111323, null))) ));
			return this1.keys.@remove(((int) (global::haxe.lang.Runtime.toInt(global::haxe.lang.Runtime.callField(k, "hashCode", 125111323, null))) ));
		}
		#line default
		
		public static object keys<K, V>(global::haxe.ds._HashMap.HashMapData<K, V> this1) {
			#line 76 "/opt/haxe/std/haxe/ds/HashMap.hx"
			return new global::haxe.ds._IntMap.IntMapValueIterator<K>(((global::haxe.ds.IntMap<K>) (this1.keys) ));
		}
		#line default
		
		public static global::haxe.ds._HashMap.HashMapData<K, V> copy<K, V>(global::haxe.ds._HashMap.HashMapData<K, V> this1) {
			#line 83 "/opt/haxe/std/haxe/ds/HashMap.hx"
			global::haxe.ds._HashMap.HashMapData<K, V> copied = new global::haxe.ds._HashMap.HashMapData<K, V>();
			copied.keys = this1.keys.copy();
			#line 85 "/opt/haxe/std/haxe/ds/HashMap.hx"
			copied.values = this1.values.copy();
			return ((global::haxe.ds._HashMap.HashMapData<K, V>) (copied) );
		}
		#line default
		
		public static object iterator<K, V>(global::haxe.ds._HashMap.HashMapData<K, V> this1) {
			#line 93 "/opt/haxe/std/haxe/ds/HashMap.hx"
			return new global::haxe.ds._IntMap.IntMapValueIterator<V>(((global::haxe.ds.IntMap<V>) (this1.values) ));
		}
		#line default
		
		public static global::haxe.iterators.HashMapKeyValueIterator<K, V> keyValueIterator<K, V>(global::haxe.ds._HashMap.HashMapData<K, V> this1) {
			#line 100 "/opt/haxe/std/haxe/ds/HashMap.hx"
			return new global::haxe.iterators.HashMapKeyValueIterator<K, V>(((global::haxe.ds._HashMap.HashMapData<K, V>) (this1) ));
		}
		#line default
		
		public static void clear<K, V>(global::haxe.ds._HashMap.HashMapData<K, V> this1) {
			#line 107 "/opt/haxe/std/haxe/ds/HashMap.hx"
			this1.keys.clear();
			this1.values.clear();
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._HashMap {
	public class HashMapData<K, V> : global::haxe.lang.HxObject, global::haxe.ds._HashMap.HashMapData {
		
		public HashMapData(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public HashMapData() {
			#line 116 "/opt/haxe/std/haxe/ds/HashMap.hx"
			global::haxe.ds._HashMap.HashMapData<object, object>.__hx_ctor_haxe_ds__HashMap_HashMapData<K, V>(((global::haxe.ds._HashMap.HashMapData<K, V>) (this) ));
		}
		#line default
		
		protected static void __hx_ctor_haxe_ds__HashMap_HashMapData<K_c, V_c>(global::haxe.ds._HashMap.HashMapData<K_c, V_c> __hx_this) {
			#line 117 "/opt/haxe/std/haxe/ds/HashMap.hx"
			__hx_this.keys = new global::haxe.ds.IntMap<K_c>();
			__hx_this.values = new global::haxe.ds.IntMap<V_c>();
		}
		#line default
		
		public static object __hx_cast<K_c_c, V_c_c>(global::haxe.ds._HashMap.HashMapData me) {
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			return ( (( me != null )) ? (me.haxe_ds__HashMap_HashMapData_cast<K_c_c, V_c_c>()) : default(object) );
		}
		#line default
		
		public virtual object haxe_ds__HashMap_HashMapData_cast<K_c, V_c>() {
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			if (( global::haxe.lang.Runtime.eq(typeof(K), typeof(K_c)) && global::haxe.lang.Runtime.eq(typeof(V), typeof(V_c)) )) {
				#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
				return this;
			}
			
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			global::haxe.ds._HashMap.HashMapData<K_c, V_c> new_me = new global::haxe.ds._HashMap.HashMapData<K_c, V_c>(global::haxe.lang.EmptyObject.EMPTY);
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			global::Array<string> fields = global::Reflect.fields(this);
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			int i = 0;
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			while (( i < fields.length )) {
				#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
				string field = fields[i++];
				#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			return new_me;
		}
		#line default
		
		public global::haxe.ds.IntMap<K> keys;
		
		public global::haxe.ds.IntMap<V> values;
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
				switch (hash) {
					case 1337394146:
					{
						#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
						this.values = ((global::haxe.ds.IntMap<V>) (global::haxe.ds.IntMap<object>.__hx_cast<V>(((global::haxe.ds.IntMap) (@value) ))) );
						#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
						return @value;
					}
					
					
					case 1191633396:
					{
						#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
						this.keys = ((global::haxe.ds.IntMap<K>) (global::haxe.ds.IntMap<object>.__hx_cast<K>(((global::haxe.ds.IntMap) (@value) ))) );
						#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
				switch (hash) {
					case 1337394146:
					{
						#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
						return this.values;
					}
					
					
					case 1191633396:
					{
						#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
						return this.keys;
					}
					
					
					default:
					{
						#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			baseArr.push("values");
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			baseArr.push("keys");
			#line 112 "/opt/haxe/std/haxe/ds/HashMap.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._HashMap {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds._HashMap.HashMapData<object, object>))]
	public interface HashMapData : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds__HashMap_HashMapData_cast<K_c, V_c>();
		
	}
}


