// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._ObjectMap {
	public sealed class ObjectMapKeyIterator<T, V> : global::haxe.lang.HxObject, global::haxe.ds._ObjectMap.ObjectMapKeyIterator {
		
		static bool __hx_init_called = false;
		static ObjectMapKeyIterator() {
			if(global::haxe.ds._ObjectMap.ObjectMapKeyIterator<object, object>.__hx_init_called) return;
			global::haxe.ds._ObjectMap.ObjectMapKeyIterator<object, object>.__hx_init_called = true;
			unchecked{
				#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{407283053, 1224901875}, new string[]{"hasNext", "next"});
			}
			
		}
		#line default
		
		public ObjectMapKeyIterator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ObjectMapKeyIterator(global::haxe.ds.ObjectMap<T, V> m) {
			#line 481 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			global::haxe.ds._ObjectMap.ObjectMapKeyIterator<object, object>.__hx_ctor_haxe_ds__ObjectMap_ObjectMapKeyIterator<T, V>(((global::haxe.ds._ObjectMap.ObjectMapKeyIterator<T, V>) (this) ), ((global::haxe.ds.ObjectMap<T, V>) (m) ));
		}
		#line default
		
		private static void __hx_ctor_haxe_ds__ObjectMap_ObjectMapKeyIterator<T_c, V_c>(global::haxe.ds._ObjectMap.ObjectMapKeyIterator<T_c, V_c> __hx_this, global::haxe.ds.ObjectMap<T_c, V_c> m) {
			#line 482 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			__hx_this.i = 0;
			__hx_this.m = m;
			#line 484 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			__hx_this.len = m.nBuckets;
		}
		#line default
		
		public static object __hx_cast<T_c_c, V_c_c>(global::haxe.ds._ObjectMap.ObjectMapKeyIterator me) {
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			return ( (( me != null )) ? (me.haxe_ds__ObjectMap_ObjectMapKeyIterator_cast<T_c_c, V_c_c>()) : default(object) );
		}
		#line default
		
		public object haxe_ds__ObjectMap_ObjectMapKeyIterator_cast<T_c, V_c>() {
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			if (( global::haxe.lang.Runtime.eq(typeof(T), typeof(T_c)) && global::haxe.lang.Runtime.eq(typeof(V), typeof(V_c)) )) {
				#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				return this;
			}
			
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			global::haxe.ds._ObjectMap.ObjectMapKeyIterator<T_c, V_c> new_me = new global::haxe.ds._ObjectMap.ObjectMapKeyIterator<T_c, V_c>(((global::haxe.lang.EmptyObject) (global::haxe.lang.EmptyObject.EMPTY) ));
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			global::Array<string> fields = global::Reflect.fields(this);
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			int i = 0;
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			while (( i < fields.length )) {
				#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				string field = fields[i++];
				#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			return new_me;
		}
		#line default
		
		public global::haxe.ds.ObjectMap<T, V> m;
		
		public int i;
		
		public int len;
		
		public bool hasNext() {
			unchecked {
				#line 488 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				{
					#line 488 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
					int _g = this.i;
					#line 488 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
					int _g1 = this.len;
					#line 488 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
					while (( _g < _g1 )) {
						#line 488 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						int j = _g++;
						if (( (( this.m.hashes[j] & -2 )) != 0 )) {
							#line 490 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
							this.i = j;
							return true;
						}
						
					}
					
				}
				
				#line 494 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				return false;
			}
			#line default
		}
		
		
		public T next() {
			unchecked {
				#line 498 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				T ret = global::haxe.lang.Runtime.genericCast<T>(this.m._keys[this.i]);
				#line 501 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				this.m.cachedIndex = this.i;
				this.m.cachedKey = ret;
				#line 505 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				this.i += 1;
				return ret;
			}
			#line default
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.len = ((int) (@value) );
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.i = ((int) (@value) );
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.len = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.i = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					case 109:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.m = ((global::haxe.ds.ObjectMap<T, V>) (global::haxe.ds.ObjectMap<object, object>.__hx_cast<T, V>(((global::haxe.ds.ObjectMap) (@value) ))) );
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 407283053:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "hasNext", 407283053)) );
					}
					
					
					case 5393365:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.len;
					}
					
					
					case 105:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.i;
					}
					
					
					case 109:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.m;
					}
					
					
					default:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return ((double) (this.len) );
					}
					
					
					case 105:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return ((double) (this.i) );
					}
					
					
					default:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.next();
					}
					
					
					case 407283053:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.hasNext();
					}
					
					
					default:
					{
						#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			baseArr.push("len");
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			baseArr.push("i");
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			baseArr.push("m");
			#line 476 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._ObjectMap {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds._ObjectMap.ObjectMapKeyIterator<object, object>))]
	public interface ObjectMapKeyIterator : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds__ObjectMap_ObjectMapKeyIterator_cast<T_c, V_c>();
		
		bool hasNext();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._ObjectMap {
	public sealed class ObjectMapValueIterator<K, T> : global::haxe.lang.HxObject, global::haxe.ds._ObjectMap.ObjectMapValueIterator {
		
		static bool __hx_init_called = false;
		static ObjectMapValueIterator() {
			if(global::haxe.ds._ObjectMap.ObjectMapValueIterator<object, object>.__hx_init_called) return;
			global::haxe.ds._ObjectMap.ObjectMapValueIterator<object, object>.__hx_init_called = true;
			unchecked{
				#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{407283053, 1224901875}, new string[]{"hasNext", "next"});
			}
			
		}
		#line default
		
		public ObjectMapValueIterator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ObjectMapValueIterator(global::haxe.ds.ObjectMap<K, T> m) {
			#line 516 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			global::haxe.ds._ObjectMap.ObjectMapValueIterator<object, object>.__hx_ctor_haxe_ds__ObjectMap_ObjectMapValueIterator<K, T>(((global::haxe.ds._ObjectMap.ObjectMapValueIterator<K, T>) (this) ), ((global::haxe.ds.ObjectMap<K, T>) (m) ));
		}
		#line default
		
		private static void __hx_ctor_haxe_ds__ObjectMap_ObjectMapValueIterator<K_c, T_c>(global::haxe.ds._ObjectMap.ObjectMapValueIterator<K_c, T_c> __hx_this, global::haxe.ds.ObjectMap<K_c, T_c> m) {
			#line 517 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			__hx_this.i = 0;
			__hx_this.m = m;
			#line 519 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			__hx_this.len = m.nBuckets;
		}
		#line default
		
		public static object __hx_cast<K_c_c, T_c_c>(global::haxe.ds._ObjectMap.ObjectMapValueIterator me) {
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			return ( (( me != null )) ? (me.haxe_ds__ObjectMap_ObjectMapValueIterator_cast<K_c_c, T_c_c>()) : default(object) );
		}
		#line default
		
		public object haxe_ds__ObjectMap_ObjectMapValueIterator_cast<K_c, T_c>() {
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			if (( global::haxe.lang.Runtime.eq(typeof(K), typeof(K_c)) && global::haxe.lang.Runtime.eq(typeof(T), typeof(T_c)) )) {
				#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				return this;
			}
			
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			global::haxe.ds._ObjectMap.ObjectMapValueIterator<K_c, T_c> new_me = new global::haxe.ds._ObjectMap.ObjectMapValueIterator<K_c, T_c>(((global::haxe.lang.EmptyObject) (global::haxe.lang.EmptyObject.EMPTY) ));
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			global::Array<string> fields = global::Reflect.fields(this);
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			int i = 0;
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			while (( i < fields.length )) {
				#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				string field = fields[i++];
				#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			return new_me;
		}
		#line default
		
		public global::haxe.ds.ObjectMap<K, T> m;
		
		public int i;
		
		public int len;
		
		public bool hasNext() {
			unchecked {
				#line 523 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				{
					#line 523 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
					int _g = this.i;
					#line 523 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
					int _g1 = this.len;
					#line 523 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
					while (( _g < _g1 )) {
						#line 523 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						int j = _g++;
						if (( (( this.m.hashes[j] & -2 )) != 0 )) {
							#line 525 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
							this.i = j;
							return true;
						}
						
					}
					
				}
				
				#line 529 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				return false;
			}
			#line default
		}
		
		
		public T next() {
			unchecked {
				#line 533 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				T ret = global::haxe.lang.Runtime.genericCast<T>(this.m.vals[this.i]);
				this.i += 1;
				#line 535 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				return ret;
			}
			#line default
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.len = ((int) (@value) );
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.i = ((int) (@value) );
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.len = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.i = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					case 109:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						this.m = ((global::haxe.ds.ObjectMap<K, T>) (global::haxe.ds.ObjectMap<object, object>.__hx_cast<K, T>(((global::haxe.ds.ObjectMap) (@value) ))) );
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 407283053:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "hasNext", 407283053)) );
					}
					
					
					case 5393365:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.len;
					}
					
					
					case 105:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.i;
					}
					
					
					case 109:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.m;
					}
					
					
					default:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return ((double) (this.len) );
					}
					
					
					case 105:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return ((double) (this.i) );
					}
					
					
					default:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.next();
					}
					
					
					case 407283053:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return this.hasNext();
					}
					
					
					default:
					{
						#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			baseArr.push("len");
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			baseArr.push("i");
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			baseArr.push("m");
			#line 511 "/opt/haxe/std/cs/_std/haxe/ds/ObjectMap.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._ObjectMap {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds._ObjectMap.ObjectMapValueIterator<object, object>))]
	public interface ObjectMapValueIterator : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds__ObjectMap_ObjectMapValueIterator_cast<K_c, T_c>();
		
		bool hasNext();
		
	}
}


