// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._ReadOnlyArray {
	public sealed class ReadOnlyArray_Impl_ {
		
		
		
		public static int get_length<T>(global::Array<T> this1) {
			#line 41 "/opt/haxe/std/haxe/ds/ReadOnlyArray.hx"
			return this1.length;
		}
		#line default
		
		public static T @get<T>(global::Array<T> this1, int i) {
			#line 44 "/opt/haxe/std/haxe/ds/ReadOnlyArray.hx"
			return this1[i];
		}
		#line default
		
	}
}


