// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._StringMap {
	public sealed class StringMapKeyIterator<T> : global::haxe.lang.HxObject, global::haxe.ds._StringMap.StringMapKeyIterator {
		
		static bool __hx_init_called = false;
		static StringMapKeyIterator() {
			if(global::haxe.ds._StringMap.StringMapKeyIterator<object>.__hx_init_called) return;
			global::haxe.ds._StringMap.StringMapKeyIterator<object>.__hx_init_called = true;
			unchecked{
				#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{407283053, 1224901875}, new string[]{"hasNext", "next"});
			}
			
		}
		#line default
		
		public StringMapKeyIterator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public StringMapKeyIterator(global::haxe.ds.StringMap<T> m) {
			#line 479 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			global::haxe.ds._StringMap.StringMapKeyIterator<object>.__hx_ctor_haxe_ds__StringMap_StringMapKeyIterator<T>(((global::haxe.ds._StringMap.StringMapKeyIterator<T>) (this) ), ((global::haxe.ds.StringMap<T>) (m) ));
		}
		#line default
		
		private static void __hx_ctor_haxe_ds__StringMap_StringMapKeyIterator<T_c>(global::haxe.ds._StringMap.StringMapKeyIterator<T_c> __hx_this, global::haxe.ds.StringMap<T_c> m) {
			#line 480 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			__hx_this.m = m;
			__hx_this.i = 0;
			#line 482 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			__hx_this.len = m.nBuckets;
		}
		#line default
		
		public static object __hx_cast<T_c_c>(global::haxe.ds._StringMap.StringMapKeyIterator me) {
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			return ( (( me != null )) ? (me.haxe_ds__StringMap_StringMapKeyIterator_cast<T_c_c>()) : default(object) );
		}
		#line default
		
		public object haxe_ds__StringMap_StringMapKeyIterator_cast<T_c>() {
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			if (global::haxe.lang.Runtime.eq(typeof(T), typeof(T_c))) {
				#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				return this;
			}
			
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			global::haxe.ds._StringMap.StringMapKeyIterator<T_c> new_me = new global::haxe.ds._StringMap.StringMapKeyIterator<T_c>(((global::haxe.lang.EmptyObject) (global::haxe.lang.EmptyObject.EMPTY) ));
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			global::Array<string> fields = global::Reflect.fields(this);
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			int i = 0;
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			while (( i < fields.length )) {
				#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				string field = fields[i++];
				#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			return new_me;
		}
		#line default
		
		public global::haxe.ds.StringMap<T> m;
		
		public int i;
		
		public int len;
		
		public bool hasNext() {
			unchecked {
				#line 486 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				{
					#line 486 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
					int _g = this.i;
					#line 486 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
					int _g1 = this.len;
					#line 486 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
					while (( _g < _g1 )) {
						#line 486 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						int j = _g++;
						if (( (( this.m.hashes[j] & -2 )) != 0 )) {
							#line 488 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
							this.i = j;
							return true;
						}
						
					}
					
				}
				
				#line 492 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				return false;
			}
			#line default
		}
		
		
		public string next() {
			#line 496 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			string ret = ((string) (this.m._keys[this.i]) );
			#line 498 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			this.m.cachedIndex = this.i;
			this.m.cachedKey = ret;
			#line 501 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			this.i++;
			return ret;
		}
		#line default
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.len = ((int) (@value) );
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.i = ((int) (@value) );
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.len = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.i = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					case 109:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.m = ((global::haxe.ds.StringMap<T>) (global::haxe.ds.StringMap<object>.__hx_cast<T>(((global::haxe.ds.StringMap) (@value) ))) );
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 407283053:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "hasNext", 407283053)) );
					}
					
					
					case 5393365:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.len;
					}
					
					
					case 105:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.i;
					}
					
					
					case 109:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.m;
					}
					
					
					default:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return ((double) (this.len) );
					}
					
					
					case 105:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return ((double) (this.i) );
					}
					
					
					default:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.next();
					}
					
					
					case 407283053:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.hasNext();
					}
					
					
					default:
					{
						#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			baseArr.push("len");
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			baseArr.push("i");
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			baseArr.push("m");
			#line 474 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._StringMap {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds._StringMap.StringMapKeyIterator<object>))]
	public interface StringMapKeyIterator : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds__StringMap_StringMapKeyIterator_cast<T_c>();
		
		bool hasNext();
		
		string next();
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._StringMap {
	public sealed class StringMapValueIterator<T> : global::haxe.lang.HxObject, global::haxe.ds._StringMap.StringMapValueIterator {
		
		static bool __hx_init_called = false;
		static StringMapValueIterator() {
			if(global::haxe.ds._StringMap.StringMapValueIterator<object>.__hx_init_called) return;
			global::haxe.ds._StringMap.StringMapValueIterator<object>.__hx_init_called = true;
			unchecked{
				#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{407283053, 1224901875}, new string[]{"hasNext", "next"});
			}
			
		}
		#line default
		
		public StringMapValueIterator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public StringMapValueIterator(global::haxe.ds.StringMap<T> m) {
			#line 512 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			global::haxe.ds._StringMap.StringMapValueIterator<object>.__hx_ctor_haxe_ds__StringMap_StringMapValueIterator<T>(((global::haxe.ds._StringMap.StringMapValueIterator<T>) (this) ), ((global::haxe.ds.StringMap<T>) (m) ));
		}
		#line default
		
		private static void __hx_ctor_haxe_ds__StringMap_StringMapValueIterator<T_c>(global::haxe.ds._StringMap.StringMapValueIterator<T_c> __hx_this, global::haxe.ds.StringMap<T_c> m) {
			#line 513 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			__hx_this.m = m;
			__hx_this.i = 0;
			#line 515 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			__hx_this.len = m.nBuckets;
		}
		#line default
		
		public static object __hx_cast<T_c_c>(global::haxe.ds._StringMap.StringMapValueIterator me) {
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			return ( (( me != null )) ? (me.haxe_ds__StringMap_StringMapValueIterator_cast<T_c_c>()) : default(object) );
		}
		#line default
		
		public object haxe_ds__StringMap_StringMapValueIterator_cast<T_c>() {
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			if (global::haxe.lang.Runtime.eq(typeof(T), typeof(T_c))) {
				#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				return this;
			}
			
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			global::haxe.ds._StringMap.StringMapValueIterator<T_c> new_me = new global::haxe.ds._StringMap.StringMapValueIterator<T_c>(((global::haxe.lang.EmptyObject) (global::haxe.lang.EmptyObject.EMPTY) ));
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			global::Array<string> fields = global::Reflect.fields(this);
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			int i = 0;
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			while (( i < fields.length )) {
				#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				string field = fields[i++];
				#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				global::Reflect.setField(new_me, field, global::Reflect.field(this, field));
			}
			
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			return new_me;
		}
		#line default
		
		public global::haxe.ds.StringMap<T> m;
		
		public int i;
		
		public int len;
		
		public bool hasNext() {
			unchecked {
				#line 519 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				{
					#line 519 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
					int _g = this.i;
					#line 519 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
					int _g1 = this.len;
					#line 519 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
					while (( _g < _g1 )) {
						#line 519 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						int j = _g++;
						if (( (( this.m.hashes[j] & -2 )) != 0 )) {
							#line 521 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
							this.i = j;
							return true;
						}
						
					}
					
				}
				
				#line 525 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				return false;
			}
			#line default
		}
		
		
		public T next() {
			#line 529 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			return global::haxe.lang.Runtime.genericCast<T>(this.m.vals[this.i++]);
		}
		#line default
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.len = ((int) (@value) );
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.i = ((int) (@value) );
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.len = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					case 105:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.i = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					case 109:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						this.m = ((global::haxe.ds.StringMap<T>) (global::haxe.ds.StringMap<object>.__hx_cast<T>(((global::haxe.ds.StringMap) (@value) ))) );
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return @value;
					}
					
					
					default:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "next", 1224901875)) );
					}
					
					
					case 407283053:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "hasNext", 407283053)) );
					}
					
					
					case 5393365:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.len;
					}
					
					
					case 105:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.i;
					}
					
					
					case 109:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.m;
					}
					
					
					default:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 5393365:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return ((double) (this.len) );
					}
					
					
					case 105:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return ((double) (this.i) );
					}
					
					
					default:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
				switch (hash) {
					case 1224901875:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.next();
					}
					
					
					case 407283053:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return this.hasNext();
					}
					
					
					default:
					{
						#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			baseArr.push("len");
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			baseArr.push("i");
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			baseArr.push("m");
			#line 507 "/opt/haxe/std/cs/_std/haxe/ds/StringMap.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._StringMap {
	[global::haxe.lang.GenericInterface(typeof(global::haxe.ds._StringMap.StringMapValueIterator<object>))]
	public interface StringMapValueIterator : global::haxe.lang.IHxObject, global::haxe.lang.IGenericObject {
		
		object haxe_ds__StringMap_StringMapValueIterator_cast<T_c>();
		
		bool hasNext();
		
	}
}


