// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace _EnumValue {
	public sealed class EnumValue_Impl_ {
		
		public static bool match(object this1, object pattern) {
			#line 59 "/opt/haxe/std/EnumValue.hx"
			return false;
		}
		#line default
		
	}
}


